### ISSUE TITLE
Error: Operation unsupported

### ISSUE THREAD

**Issue by victorazevedo** [randdusing/ng-cordova-bluetoothle#15]
I´m having this error in Log when I try to connect:

Initialize Error:
{"error": "unsupported", "message" : "Operation unsupported"}

I´m using Motorola Moto X with Android version 6.0

I added in my config.xml:

```
 <plugin name="BluetoothLePlugin" value="com.randdusing.bluetoothle.BluetoothLePlugin" /> 
```

My AndroidManifest.xml I have Bluetooth Permissions:

```
<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

I´m trying to connecto to HC-05 or stick n find (ibeacons) by bluetooth with phonegap/ionic/cordova project. Someone can help me with a working example?

**Comment by randdusing** [comment]
Are you calling bluetoothle.initialize before the deviceready event has been fired?

**Comment by pngsantos** [comment]
Same issue. Using with ionic and already have it inside the $ionicPlatform.ready() wrapper.

**Comment by randdusing** [comment]
What type of device?

**Comment by victorazevedo** [comment]
Randdusing I used your example without change anything.
These examples worked with me using the cordova-plugin-ble-central: 

https://github.com/don/ionic-ble
(cordova plugin add https://github.com/don/cordova-plugin-ble-central --save)

https://software.intel.com/en-us/creating-a-bluetooth-low-energy-app

But I have to turn the GPS on to the bluetooth plugin work. Do you know why or how can i change this ?

**Comment by randdusing** [comment]
Location services must be enabled on 6.0. If you open up Android Device Monitor, do you see any issues?

**Comment by randdusing** [comment]
Actually why are you adding that to config.xml? You shouldn't need to add anything

**Comment by MathGrelck** [comment]
I'm having this issue on both LG Nexus 4 Android 5.1.1 and iPhone 5s iOS 9.3.2.
I followed the instructions for the provided example and the app runs on both devices, but I get that same error when initializing (both in peripheral mode and central). Check it out in the ionic view, id: d5fc1047

**Comment by randdusing** [comment]
Is the BLE plugin supported by Ionic View? http://docs.ionic.io/docs/view-usage

**Comment by MathGrelck** [comment]
Ups, sorry about that! I'm obviously still learning...

**Comment by randdusing** [comment]
No worries!

**Comment by Martijn-Jansen** [comment]
i'm experiencing the same issue "Operation unsupported" on every call in the sample app. I'm using iphone 6. even the initialize is returning this error.
I find it very hard to find a good plugin that works on ios and android for advertising.
Some input would be great.
[xsanyware.ionic.ble.zip](https://github.com/randdusing/ng-cordova-bluetoothle/files/403411/xsanyware.ionic.ble.zip)

**Comment by randdusing** [comment]
@Martijn-Jansen Looks like you are using the example provided. Can you try removing and then adding back the plugin? You should only see that message if the plugin fails to load.

**Comment by victorazevedo** [comment]
An alternative plugin that worked for me :
https://github.com/don/cordova-plugin-ble-central

Em sáb, 13 de ago de 2016 21:19, Rand Dusing notifications@github.com
escreveu:

**Comment by AshMartian** [comment]
I'm having this issue on iOS only, Android loads fine and is able to scan, iOS receives ` {error: "unsupported", message: "Operation unsupported"}`
Will try a few more tricks

**Comment by AshMartian** [comment]
I was able to get around this by removing the plugin, cleaning in xCode, and reinstalling before running `cordova build ios`
