### ISSUE TITLE
Read Long Characteristic 

### ISSUE THREAD

**Issue by herfedos** [randdusing/ng-cordova-bluetoothle#16]
Hi, 
as graduation project, i'm developing an hybrid application for the monitoring of vital parameter, which requires Bluetooth Low Energy. 
I'm using ng-cordova-bluetoothle plugin and all the methods that I have used so far are working. 
Now I want to read the frame from the BLE card to plot charts, but I have a problem, the frame length is 100bytes and I found that the maximum that can be read is 22bytes. have you any idea how I can use the read() to read this frame? is that even possible ?
thank you,

**Comment by randdusing** [comment]
What platform are you on?

**Comment by randdusing** [comment]
Also, this is most likely not an issue with ng-cordova-bluetoothle. I'd close this bug and open one on the plugin's repository.

**Comment by herfedos** [comment]
ok, thank you.

**Comment by randdusing** [comment]
Closing due to previous comments
