### ISSUE TITLE
not finds a bluetooth printer Qsprinter

### ISSUE THREAD

**Issue by oAllanWeb** [randdusing/ng-cordova-bluetoothle#17]
I am using the plugin but my application, but it does not finds a bluetooth printer Qsprinter

**Comment by randdusing** [comment]
Is it Bluetooth or Bluetooth LE? This plugin only supports Bluetooth LE.

**Comment by oAllanWeb** [comment]
Hi , I managed to make it work but with serial bluetooth plugins. thank you for the quick response .
