### ISSUE TITLE
Scan stopped without finding any devices

### ISSUE THREAD

**Issue by rjurado01** [randdusing/ng-cordova-bluetoothle#21]
Hello, I follow Example App steps and app start fine but when I use "Read All" example I get this log:

```
Initializing...
Finding device
Read All Error: "Scan stopped without finding any devices"
```

I run example in a "Moto E" (Android 4.4).
I have "Moto G (Android 4.4)" and "Nexus 4 (Android 5)" with bluetooth activated and visible.
If I use Android bluetooth search option it find 2 devices.
I use Android SDK 23 and I have location enabled and permission.

```
Is Location Enabled Success : {"isLocationEnabled":true}
as Permission Success : {"hasPermission":true}
```

Any help?

**Updated**

Sorry this mobile devices don't be BLE devices.
I use this plugin https://github.com/don/BluetoothSerial#discoverunpaired and it works.

**Comment by randdusing** [comment]
Yah this plugin is only for BLE.
