### ISSUE TITLE
How to create Multiconnection with multiple ble devices ?

### ISSUE THREAD

**Issue by rajxi** [randdusing/ng-cordova-bluetoothle#24]
Hi Randdusing,
Thanks for the great plugin and example app.
I am creating an ionic application using your plugin which will be able to scan ,connect,discover and read the characteristics of glucometer and oximeter which are present within the range. so i need to implement multiconnection with multiple services along with monitoring of the characteristics value through subscription and notification.Currently I am able to read only one device at a time.It would be great if you can provide some inputs or examples.

**Comment by randdusing** [comment]
The example already allows you to connect to multiple devices simultaneously via user input. You should be able to reuse most of the code, but just have the scan code automatically start a connection when a glucometer or oximeter is detected.
