### ISSUE TITLE
operation unsupported

### ISSUE THREAD

**Issue by Amarpret** [randdusing/ng-cordova-bluetoothle#30]
cordova bluetoothle all operation return this error:
 error:{
"error":"unsupported","message":"operation unsupported"
}
what is soluction

**Comment by randdusing** [comment]
Either the plugin wasn't properly installed or it's being user on an improper environment like Browser.

**Comment by Amarpret** [comment]
i am installed cordova plugin add cordova-plugin-bluetoothle

**Comment by randdusing** [comment]
Try out the Ionic based example

**Comment by Amarpret** [comment]
i am confuse, basically i want to read the value from BLE device from my ionic app. what i do.

**Comment by randdusing** [comment]
Example is your best resource if you're already using Ionic
