### ISSUE TITLE
Missing template files?

### ISSUE THREAD

**Issue by majorbytes** [randdusing/ng-cordova-bluetoothle#4]
Where are these located:
type=text/ng-template id=home.html
type=text/ng-template id=device.html
type=text/ng-template id=service.html
type=text/ng-template id=characteristic.html

**Comment by randdusing** [comment]
The templates within the index.html file in the example.

**Comment by majorbytes** [comment]
It comes up all wonky in android on the screen..

**Comment by randdusing** [comment]
Wonky? Can you take a screenshot

**Comment by majorbytes** [comment]
http://topofire.dbs.umt.edu/tmp/BluetoothScreenshot.png

**Comment by randdusing** [comment]
It looks fine to me. What issue are you having?

**Comment by majorbytes** [comment]
Ok, if that is what it is supposed to look like...
Sorry, I was expecting tabbed pages or something..

**Comment by randdusing** [comment]
Yah, it's just an example :)

**Comment by majorbytes** [comment]
Thanks...  Trying to write a frontend to a Kestrel weather device and i found your github..
