### ISSUE TITLE
Can't get example app to work

### ISSUE THREAD

**Issue by jensstruemper** [randdusing/ng-cordova-bluetoothle#9]
Hi Rand, 
for some reason I can't get your example app to work. It shows the "Central role" screen only, but I'm sure I've previously seen the footer with "Peripherals" & "Log" as well. Also, non of the buttons triggers an action. I'm working on Android. Any guess what I've might done wrong?

Thanks,
Jens

<img width="516" alt="screen shot 2016-03-14 at 09 53 20" src="https://cloud.githubusercontent.com/assets/7290235/13739466/9d3e4dda-e9cb-11e5-81fb-1e5767ce5614.png">

**Comment by jensstruemper** [comment]
Arg, sorry, posted to early. I had mixed up default and dev branch. Now it is working! Thanks for your work on this!

**Comment by randdusing** [comment]
No problem, glad you got it working!
